Main page
SE-E23-SP3/web-technology-project pull request #12
Opened 2023-11-26 16:27 UTC by Anders-Bacon

Currently i am working on the Carousel of the frontpage and making that work in a hard coded format. 
The same can be said for the category part of the page, the component has been made and can just be copied, but isnt really styled or anything yet

2023-11-29 10:55 UTC, Anders-Bacon commented
Currently the only thing the frontpage needs is a connection to the database so that the right content can be displayed

2023-12-11 13:11 UTC, Anders-Bacon commented
Main page is done now, with both my indivdual extension and other things. Everything now has php variables and uses the data from the database

2023-12-13 09:30 UTC, MidnightRocket requested changes
Separate individual from group work before merge can happen

2023-12-13 09:50 UTC, MidnightRocket requested changes

2023-12-13 09:50 UTC, MidnightRocket commented on app/Http/Controllers/categoryController.php
Please rename to UpperCamel case

2023-12-13 09:50 UTC, MidnightRocket commented on routes/web.php
> +use App\Http\Controllers\categoryController;
And rename here please

2023-12-13 09:54 UTC, Anders-Bacon commented on app/Http/Controllers/categoryController.php
Done

2023-12-13 09:54 UTC, Anders-Bacon commented on routes/web.php
> +use App\Http\Controllers\categoryController;
done

2023-12-13 11:31 UTC, MidnightRocket requested changes

2023-12-13 11:31 UTC, MidnightRocket commented on resources/views/components/layouts/base.blade.php
> +        <link rel="stylesheet" href="{{asset('css/app.css')}}">
This line can be removed

2023-12-13 11:31 UTC, MidnightRocket commented on app/Http/Controllers/categoryController.php
Should be renamed to CamelCase

2023-12-13 11:40 UTC, Anders-Bacon commented on app/Http/Controllers/categoryController.php
Done

2023-12-13 12:46 UTC, MidnightRocket approved these changes
Looks good now

2023-12-13 12:55 UTC, merged